name: workflow1

on: [push]

jobs:

  build:
  
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout commit
        uses: actions/checkout@v2
        with:
          ref: 'feature'
        
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
        
      - name: Tests unitarios
        run: mvn -B '-Dtest=es.urjc.code.daw.library.unitary*Test' test 
